<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Click me_1</name>
   <tag></tag>
   <elementGuidId>f13b8dc5-2e31-4c7a-ba08-1b5f62600c34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='confirmButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#confirmButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1fcd8cda-5e3b-4252-b325-5ed500b0b352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmButton</value>
      <webElementGuid>14ca824e-9425-42d9-b894-bdcc9eb5d3d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ab07a19a-c2eb-4ab0-9cf7-ff3fd35f7fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>d9ab001d-4271-4ebe-bd66-b0af8f256329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click me</value>
      <webElementGuid>2c48d11b-897d-4910-89cf-e1ce8572611c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmButton&quot;)</value>
      <webElementGuid>17a24cef-8f10-45ad-9422-11d62c3187a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='confirmButton']</value>
      <webElementGuid>8dca93d9-32c6-44dd-88c5-6efe223981cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='javascriptAlertsWrapper']/div[3]/div[2]/button</value>
      <webElementGuid>b0aa263d-94f0-43db-a73b-8aa2638f83ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On button click, confirm box will appear'])[1]/following::button[1]</value>
      <webElementGuid>6eaece7c-a1f4-4068-9123-c7c90c07bed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click me'])[2]/following::button[1]</value>
      <webElementGuid>b76ad277-9fea-4f81-8776-ef84e0ee1eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On button click, prompt box will appear'])[1]/preceding::button[1]</value>
      <webElementGuid>bd9c61e4-34b0-440a-b6a5-11ecd5e6bc43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click me'])[4]/preceding::button[1]</value>
      <webElementGuid>71aeb8e0-4699-4276-ada9-0a8485d64dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/button</value>
      <webElementGuid>185a5606-55fd-4cc7-b6e6-36bd40fc0222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'confirmButton' and @type = 'button' and (text() = 'Click me' or . = 'Click me')]</value>
      <webElementGuid>ff92d819-cba3-46c8-9d61-f9985879dcff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
