<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Book Store API_frame2</name>
   <tag></tag>
   <elementGuidId>c7505cbb-7a2a-4bd8-8d5e-427cca6f1aa4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='frame2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frame2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>70fbea7f-cac9-41ec-9e0b-fce2a1def8e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/sample</value>
      <webElementGuid>20f87d5a-7df9-418c-981f-a4faf09646a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frame2</value>
      <webElementGuid>b01631e6-2e69-4861-ad80-4764568e1119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100px</value>
      <webElementGuid>9d6eed51-2144-4332-9bca-c72d9489c3fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100px</value>
      <webElementGuid>71488dcb-a50b-4ba3-983a-568f5dd4f1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frame2&quot;)</value>
      <webElementGuid>303a2fd9-6987-4349-88ea-b6acddf2aaca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='frame2']</value>
      <webElementGuid>6507a797-e672-45fd-8b00-7a3ee0c1d6b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame2Wrapper']/iframe</value>
      <webElementGuid>73f4e004-9261-4b51-9ba1-6069f3b06145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/iframe</value>
      <webElementGuid>08995535-8b39-467f-9df1-79acbfc426de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/sample' and @id = 'frame2']</value>
      <webElementGuid>b653d3e5-66f0-4229-a54f-3f5d6529cd3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
