<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Book Store API_frame1</name>
   <tag></tag>
   <elementGuidId>b67138bd-8ac5-4047-ab00-a9ee20b9e0fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='frame1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frame1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>73ba1d47-22e4-464d-929f-a9681dd65835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/sample</value>
      <webElementGuid>20e05ca6-bfcd-47c9-b7a7-f58d13a49718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frame1</value>
      <webElementGuid>0c3893f3-45e0-4853-af9f-1f349e6bb86a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>500px</value>
      <webElementGuid>ab0d4610-d216-4b7e-8fae-1d2be7757e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>350px</value>
      <webElementGuid>ad2db60c-5289-485b-9afd-55333a74c357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frame1&quot;)</value>
      <webElementGuid>af7ae8a1-92db-42d8-843c-14d3e0c8d826</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='frame1']</value>
      <webElementGuid>0d907951-5da4-4563-a083-a124747d0992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame1Wrapper']/iframe</value>
      <webElementGuid>a42addf1-4362-4fe1-9594-860f2993fabd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>a04e2371-d1fe-49be-aaca-622a197e3318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/sample' and @id = 'frame1']</value>
      <webElementGuid>68b2244b-e5c1-40b6-af27-2c61c504d7f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
